import type { Patient, Examination, ImageItem, Lesion, Report, Followup } from '../types';

export const mockPatients: Patient[] = [
  {
    id: 'P001',
    name: '张建国',
    gender: '男',
    age: 58,
    idCard: '110105196803125678',
    phone: '13800138001',
    chiefComplaint: '反复上腹痛3月，黑便1周',
    allergyHistory: ['青霉素过敏'],
    bmi: 26.3,
    appointmentDate: '2026-06-09',
    pastHistory: [
      {
        id: 'PE001',
        date: '2024-03-15',
        hospital: '北京协和医院',
        type: '胃镜',
        diagnosis: '慢性萎缩性胃炎（C-1型），Hp(+)，已行根除治疗',
      },
      {
        id: 'PE002',
        date: '2023-08-20',
        hospital: '北京大学第一医院',
        type: '肠镜',
        diagnosis: '结肠多发息肉（2枚，管状腺瘤，低级别瘤变），已切除',
      },
    ],
    labResults: [
      { name: 'Hb', value: '102', unit: 'g/L', reference: '130-175', abnormal: true },
      { name: '幽门螺杆菌（C13）', value: '阴性', unit: 'DOB<4', reference: '<4' },
      { name: 'CEA', value: '3.2', unit: 'ng/mL', reference: '<5' },
      { name: 'CA19-9', value: '8.6', unit: 'U/mL', reference: '<37' },
      { name: '粪便潜血', value: '阳性', unit: '', reference: '阴性', abnormal: true },
    ],
  },
  {
    id: 'P002',
    name: '李秀英',
    gender: '女',
    age: 64,
    idCard: '110108196210082345',
    phone: '13900139002',
    chiefComplaint: '体检便潜血阳性，要求行肠镜检查',
    allergyHistory: [],
    bmi: 24.1,
    appointmentDate: '2026-06-09',
    pastHistory: [
      {
        id: 'PE003',
        date: '2021-11-10',
        hospital: '解放军总医院',
        type: '肠镜',
        diagnosis: '升结肠息肉（管状腺瘤），EMR切除',
      },
    ],
    labResults: [
      { name: 'Hb', value: '138', unit: 'g/L', reference: '115-150' },
      { name: 'CEA', value: '2.8', unit: 'ng/mL', reference: '<5' },
      { name: '粪便潜血', value: '弱阳性', unit: '', reference: '阴性', abnormal: true },
    ],
  },
  {
    id: 'P003',
    name: '王大伟',
    gender: '男',
    age: 45,
    idCard: '110102198105198765',
    phone: '13700137003',
    chiefComplaint: '反酸、烧心2年，加重1月',
    allergyHistory: ['磺胺类'],
    bmi: 28.9,
    appointmentDate: '2026-06-09',
    pastHistory: [],
    labResults: [
      { name: 'Hb', value: '156', unit: 'g/L', reference: '130-175' },
      { name: '幽门螺杆菌', value: '阴性', unit: '', reference: '阴性' },
      { name: '肝功能', value: '正常', unit: '', reference: '' },
    ],
  },
];

export const mockExaminations: Examination[] = [
  {
    id: 'E001',
    patientId: 'P001',
    type: '胃肠镜',
    examDate: '2026-06-09',
    examTime: '09:30',
    room: '内镜中心-1室',
    anesthesiaType: '静脉麻醉',
    preoperativeDiagnosis: '上消化道出血原因待查；慢性萎缩性胃炎随访',
    bostonScore: 8,
    asaGrade: 'ASA II',
    endoscopeModel: '奥林巴斯 GIF-HQ290 + CF-HQ290',
    insertionTime: '09:35',
    deepestReached: '盲肠（回盲瓣）',
    withdrawalTime: '10:18',
    operatorName: '陈主任',
    assistantName: '刘技师',
    consumables: [
      { name: '一次性活检钳', quantity: 6, batchNo: 'BX20260601' },
      { name: '止血夹（可旋转）', quantity: 2, batchNo: 'HX20260508' },
      { name: '黏膜染色剂（靛胭脂）', quantity: 1, batchNo: 'DY20260301' },
    ],
    contraindications: [],
    status: 'in_progress',
    preoperativeMedication: '地西泮5mg肌注，东莨菪碱0.3mg肌注',
    processNotes: '术中胃镜见胃角溃疡及胃体后壁凹陷性病变，分别活检；肠镜顺利到达回盲部，乙状结肠及横结肠见息肉样病变，分别处理。过程平稳，麻醉苏醒良好，未出现并发症。',
  },
  {
    id: 'E002',
    patientId: 'P002',
    type: '肠镜',
    examDate: '2026-06-09',
    examTime: '10:45',
    room: '内镜中心-2室',
    anesthesiaType: '静脉麻醉',
    preoperativeDiagnosis: '结肠息肉术后3年随访；便潜血阳性',
    bostonScore: 7,
    asaGrade: 'ASA I',
    endoscopeModel: '奥林巴斯 CF-HQ290',
    insertionTime: '10:50',
    deepestReached: '盲肠',
    withdrawalTime: '11:25',
    operatorName: '赵副主任',
    assistantName: '周技师',
    consumables: [
      { name: '一次性圈套器', quantity: 2, batchNo: 'SN20260602' },
      { name: '一次性活检钳', quantity: 4, batchNo: 'BX20260601' },
    ],
    contraindications: [],
    status: 'pending',
    preoperativeMedication: '',
    processNotes: '',
  },
  {
    id: 'E003',
    patientId: 'P003',
    type: '胃镜',
    examDate: '2026-06-09',
    examTime: '11:30',
    room: '内镜中心-3室',
    anesthesiaType: '口咽局部麻醉',
    preoperativeDiagnosis: '胃食管反流病可能',
    bostonScore: 0,
    asaGrade: 'ASA I',
    endoscopeModel: '奥林巴斯 GIF-HQ290',
    insertionTime: '',
    deepestReached: '',
    withdrawalTime: '',
    operatorName: '孙医师',
    assistantName: '吴技师',
    consumables: [],
    contraindications: [],
    status: 'pending',
    preoperativeMedication: '',
    processNotes: '',
  },
];

const generateImageUrl = (seed: string) => {
  const id = Math.abs(seed.split('').reduce((a, c) => a + c.charCodeAt(0), 0)) % 1000;
  return `https://picsum.photos/seed/endo-${seed}-${id}/600/480`;
};

export const mockImages: ImageItem[] = [
  {
    id: 'IMG001',
    examId: 'E001',
    location: '食管下段',
    url: generateImageUrl('esophagus-lower'),
    description: '食管下段距门齿38cm，见纵形充血带',
    capturedAt: '09:40:15',
    annotations: [],
  },
  {
    id: 'IMG002',
    examId: 'E001',
    location: '胃角',
    url: generateImageUrl('gastric-angled'),
    description: '胃角中央可见一约1.2cm溃疡，底覆黄白苔',
    capturedAt: '09:48:30',
    annotations: [],
  },
  {
    id: 'IMG003',
    examId: 'E001',
    location: '胃体上部后壁',
    url: generateImageUrl('gastric-body'),
    description: '胃体上部后壁见不规则凹陷性病变，边界不清',
    capturedAt: '09:51:22',
    annotations: [],
  },
  {
    id: 'IMG004',
    examId: 'E001',
    location: '胃窦',
    url: generateImageUrl('gastric-antrum'),
    description: '胃窦黏膜充血水肿，红白相间',
    capturedAt: '09:55:10',
    annotations: [],
  },
  {
    id: 'IMG005',
    examId: 'E001',
    location: '十二指肠球部',
    url: generateImageUrl('duodenum-bulb'),
    description: '十二指肠球部前壁见线状浅溃疡',
    capturedAt: '09:58:45',
    annotations: [],
  },
  {
    id: 'IMG006',
    examId: 'E001',
    location: '乙状结肠',
    url: generateImageUrl('sigmoid-colon'),
    description: '乙状结肠距肛门22cm，见0.8cm带蒂息肉',
    capturedAt: '10:05:20',
    annotations: [],
  },
  {
    id: 'IMG007',
    examId: 'E001',
    location: '横结肠肝曲',
    url: generateImageUrl('transverse-colon'),
    description: '横结肠肝曲见1.5cm颗粒型侧向发育病变',
    capturedAt: '10:10:55',
    annotations: [],
  },
  {
    id: 'IMG008',
    examId: 'E001',
    location: '回盲部',
    url: generateImageUrl('ileocecal'),
    description: '回盲部回盲瓣形态正常',
    capturedAt: '10:14:30',
    annotations: [],
  },
  {
    id: 'IMG009',
    examId: 'E002',
    location: '升结肠',
    url: generateImageUrl('ascending-colon'),
    description: '升结肠见多发憩室',
    capturedAt: '11:02:15',
    annotations: [],
  },
  {
    id: 'IMG010',
    examId: 'E002',
    location: '降结肠',
    url: generateImageUrl('descending-colon'),
    description: '降结肠见约1.0cm广基息肉，表面分叶',
    capturedAt: '11:10:40',
    annotations: [],
  },
  {
    id: 'IMG011',
    examId: 'E003',
    location: '食管中段',
    url: generateImageUrl('esophagus-mid'),
    description: '食管黏膜光滑，血管纹理清晰',
    capturedAt: '',
    annotations: [],
  },
  {
    id: 'IMG012',
    examId: 'E003',
    location: '胃底',
    url: generateImageUrl('gastric-fundus'),
    description: '胃底黏膜光滑',
    capturedAt: '',
    annotations: [],
  },
];

export const mockLesions: Lesion[] = [
  {
    id: 'L001',
    examId: 'E001',
    location: '胃角中央',
    sizeMajor: 1.2,
    sizeMinor: 0.8,
    morphology: '溃疡型',
    surfaceFeature: '黄白苔附着、边缘充血',
    forrestGrade: 'II a：裸露血管',
    activeBleeding: false,
    preliminaryDiagnosis: ['胃溃疡（A1期）', '不排除早期胃癌'],
    notes: '溃疡边缘尚规整，周围黏膜纠集，已于边缘及中央各取活检2块',
    imageIds: ['IMG002'],
    biopsy: {
      site: '胃角溃疡边缘+中央',
      forcepsCount: 4,
      specimenNos: ['B1', 'B2', 'B3', 'B4'],
    },
  },
  {
    id: 'L002',
    examId: 'E001',
    location: '胃体上部后壁',
    sizeMajor: 1.5,
    sizeMinor: 1.0,
    morphology: '平坦凹陷型（IIc）',
    surfaceFeature: '黏膜粗糙、颗粒感、边界不清',
    forrestGrade: '',
    activeBleeding: false,
    preliminaryDiagnosis: ['早期胃癌（凹陷型）', '慢性溃疡瘢痕'],
    notes: '靛胭脂染色后边界较前清晰，已靶向活检',
    imageIds: ['IMG003'],
    biopsy: {
      site: '胃体上部后壁病变处',
      forcepsCount: 6,
      specimenNos: ['B5', 'B6', 'B7', 'B8', 'B9', 'B10'],
    },
  },
  {
    id: 'L003',
    examId: 'E001',
    location: '食管下段',
    sizeMajor: 2.0,
    sizeMinor: 0,
    morphology: '平坦型（IIb）',
    surfaceFeature: '纵形糜烂、充血水肿',
    forrestGrade: '',
    activeBleeding: false,
    preliminaryDiagnosis: ['反流性食管炎（LA-B级）'],
    notes: '融合约半周径，齿状线略上移',
    imageIds: ['IMG001'],
    biopsy: null,
  },
  {
    id: 'L004',
    examId: 'E001',
    location: '乙状结肠（距肛门22cm）',
    sizeMajor: 0.8,
    sizeMinor: 0.7,
    morphology: '隆起型（Ip）',
    surfaceFeature: '分叶状、色泽略红',
    forrestGrade: '',
    activeBleeding: false,
    preliminaryDiagnosis: ['结肠管状腺瘤'],
    notes: '已行圈套切除，残端止血夹1枚',
    imageIds: ['IMG006'],
    biopsy: {
      site: '乙状结肠息肉',
      forcepsCount: 0,
      specimenNos: ['P001'],
    },
  },
  {
    id: 'L005',
    examId: 'E001',
    location: '横结肠肝曲',
    sizeMajor: 1.5,
    sizeMinor: 1.2,
    morphology: '平坦隆起型（IIa）',
    surfaceFeature: '颗粒型、中央略凹陷',
    forrestGrade: '',
    activeBleeding: false,
    preliminaryDiagnosis: ['结肠侧向发育型肿瘤（LST-G）', '绒毛状腺瘤'],
    notes: '建议行ESD治疗，已活检2块',
    imageIds: ['IMG007'],
    biopsy: {
      site: '横结肠肝曲病变',
      forcepsCount: 2,
      specimenNos: ['B11', 'B12'],
    },
  },
  {
    id: 'L006',
    examId: 'E002',
    location: '降结肠',
    sizeMajor: 1.0,
    sizeMinor: 0.9,
    morphology: '隆起型（Is）',
    surfaceFeature: '分叶状',
    forrestGrade: '',
    activeBleeding: false,
    preliminaryDiagnosis: ['结肠管状腺瘤'],
    notes: '',
    imageIds: ['IMG010'],
    biopsy: null,
  },
];

export const mockReports: Report[] = [
  {
    id: 'R001',
    examId: 'E001',
    structuredFindings: '',
    insertedTerms: [],
    diagnosis: '',
    recommendations: '',
    conclusion: '',
    doctorSignature: '',
    signedAt: '',
    completenessScore: 0,
    missingFields: [],
    lastEditedAt: '2026-06-09 09:35',
  },
  {
    id: 'R002',
    examId: 'E002',
    structuredFindings: '',
    insertedTerms: [],
    diagnosis: '',
    recommendations: '',
    conclusion: '',
    doctorSignature: '',
    signedAt: '',
    completenessScore: 0,
    missingFields: [],
    lastEditedAt: '2026-06-09 10:40',
  },
  {
    id: 'R003',
    examId: 'E003',
    structuredFindings: '',
    insertedTerms: [],
    diagnosis: '',
    recommendations: '',
    conclusion: '',
    doctorSignature: '',
    signedAt: '',
    completenessScore: 0,
    missingFields: [],
    lastEditedAt: '',
  },
];

export const mockFollowups: Followup[] = [
  {
    id: 'F001',
    patientId: 'P001',
    patientName: '张建国',
    reason: '早期胃癌待病理回报 / 胃溃疡（Forrest IIa）',
    plannedDate: '2026-07-09',
    riskLevel: 'high',
    status: 'pending',
    reminderType: '短信+电话',
    reviewResult: '',
    createdAt: '2026-06-09',
  },
  {
    id: 'F002',
    patientId: 'P001',
    patientName: '张建国',
    reason: '结肠息肉术后+LST随访',
    plannedDate: '2027-06-09',
    riskLevel: 'medium',
    status: 'pending',
    reminderType: '短信',
    reviewResult: '',
    createdAt: '2026-06-09',
  },
  {
    id: 'F003',
    patientId: 'P002',
    patientName: '李秀英',
    reason: '结肠息肉术后3年复查',
    plannedDate: '2026-06-01',
    riskLevel: 'medium',
    status: 'overdue',
    reminderType: '电话+家属通知',
    reviewResult: '',
    createdAt: '2026-05-01',
  },
  {
    id: 'F004',
    patientId: 'P003',
    patientName: '王大伟',
    reason: '反流性食管炎PPI治疗后复查',
    plannedDate: '2026-08-15',
    riskLevel: 'low',
    status: 'completed',
    reminderType: 'APP推送',
    reviewResult: '2026-08-20复查：食管黏膜愈合良好，LA分级改善至A级',
    createdAt: '2026-05-15',
  },
  {
    id: 'F005',
    patientId: 'P001',
    patientName: '张建国',
    reason: '病理回报提示高级别瘤变',
    plannedDate: '2026-06-16',
    riskLevel: 'high',
    status: 'pending',
    reminderType: '电话+立即处理',
    reviewResult: '',
    createdAt: '2026-06-10',
  },
];

export const anatomyLocations = [
  { name: '食管', children: ['上段', '中段', '下段', '贲门'] },
  {
    name: '胃',
    children: ['胃底', '胃体（前壁/后壁/大弯/小弯）', '胃角', '胃窦', '幽门'],
  },
  { name: '十二指肠', children: ['球部', '降部', '乳头区'] },
  {
    name: '结直肠',
    children: ['直肠', '乙状结肠', '降结肠', '脾曲', '横结肠', '肝曲', '升结肠', '盲肠/回盲部'],
  },
];
